### ISSUE TITLE
I met this error when run your install script

### ISSUE THREAD

**Issue by bemoregt** [JM-Lab/cli-genie#1]
Hi, @JM-Lab 

I met this error when run your install script on my m1 mac(맥미니).

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1806  100  1806    0     0   2990      0 --:--:-- --:--:-- --:--:--  3015
Password:
Cloning into 'cli-genie'...
remote: Enumerating objects: 204, done.
remote: Counting objects: 100% (204/204), done.
remote: Compressing objects: 100% (94/94), done.
remote: Total 204 (delta 69), reused 181 (delta 51), pack-reused 0
Receiving objects: 100% (204/204), 1.45 MiB | 2.25 MiB/s, done.
Resolving deltas: 100% (69/69), done.
The operation couldn’t be completed. Unable to locate a Java Runtime.
Please visit http://www.java.com for information on installing Java.

cp: bin/cg: No such file or directory
cli-genie installation is complete.
rocket@rock ~ % 
rocket@rock ~ % 
rocket@rock ~ % 
rocket@rock ~ % 
rocket@rock ~ % cg
zsh: command not found: cg
---------------------

What's wrong to me?

Thanks in advance.
@bemoregt.

**Comment by JM-Lab** [comment]
@bemoregt The error message you received suggests that Java may not have been installed properly on your Mac, and the install script may be trying to use Homebrew to automatically install dependencies. However, Homebrew is not installed by default on Macs. To fix this, you can install Homebrew by running this command in your Terminal:

/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

Once Homebrew is installed, try running the install script again to see if the issue has been resolved.
